### ISSUE TITLE
SFrame throwing various errors when output-ing or retrieving a specific row

### ISSUE THREAD

**Issue by alvations** [dato-code/SFrame#127]
There's some problems with my SFrame that I've loaded but it just can't seem to dump into a binary or csv format. **Is it a memory issue or is it how SFrame works such that NoneType appears often when iterating or saving the SFrame?**

For more information, see http://stackoverflow.com/questions/34654901/how-do-i-find-specific-rows-that-throws-an-error-when-saving-in-graphlab-sframe

**Comment by TobyRoseman** [comment]
@alvations - Sorry to hear you're having this issue. Would it be possible for you to share the data you used to create the SFrame?

**Comment by alvations** [comment]
@TobyRoseman Thanks for looking into this!

I figured out the error when I did quite a lot of `SFrame.apply()` manipulation and afterwards when it materializes before saving, there were columns that are weird. Strangely, `SFrame.fillna(0)` and `SFrame.dropna(0)` didn't seem to work. So I went back to every column that I've added to the final `SFrame` and check through each row and found that there were string columns that I've evaluated with `eval(str)` and the string is the python keyword `None`. Nevertheless, `SFrame.fillna(0)` didn't fill the `None`, so I figured that `SFrame.fillna(0)` fills empty cells but not `None` cells for `eval(str)` types. 

To access that big SFrame that was giving me trouble, `git clone https://github.com/alvations/stasis.git` and then:

```python
from __future__ import division

import os
import string
from itertools import chain

import graphlab

from nltk.corpus import wordnet as wn
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk import pos_tag, word_tokenize

sts = graphlab.SFrame.read_csv('sts.csv', delimiter='\t', column_type_hints=[str, str, float, str, str], quote_char='\0')
asiya = graphlab.SFrame.read_csv('sts_asiya.csv', delimiter='\t', quote_char='\0')
meteor = graphlab.SFrame.read_csv('sts_meteor.csv', delimiter='\t', quote_char='\0')
beer_reval = graphlab.SFrame.read_csv('sts_beer_reval.csv', delimiter='\t', quote_char='\0')
mwa = graphlab.SFrame.read_csv('sts_mwa.csv', delimiter='\t', column_type_hints=[str,str], quote_char='\0')

assert len(sts) == len(asiya) == len(meteor) == len(beer_reval) == len(mwa)

sts['Sent1_tokenized']  = graphlab.text_analytics.tokenize(sts['Sent1'], to_lower=False)
sts['Sent2_tokenized']  = graphlab.text_analytics.tokenize(sts['Sent2'], to_lower=False)

sts['Sent1_len'] = sts.apply(lambda x: len(x['Sent1_tokenized']))
sts['Sent2_len'] = sts.apply(lambda x: len(x['Sent2_tokenized']))

stoplist = graphlab.text_analytics.stopwords(lang='en')
punctuations = string.punctuation
stoplist.update(set(punctuations))
C = set(w.strip(punctuations).lower() for w in chain(*sts['Sent1_tokenized']) if w not in stoplist)
C.remove('')

#mwa['num_mwa'] = mwa.apply(lambda x: len(eval(x['MWA_Id'])))
#print mwa['num_mwa'].head(), sts['Sent1_len'].head(), sts['Sent2_len'].head()

numerator_s1 = mwa.apply(lambda x: sum(alignments[0] in C if alignments else 0 for alignments in eval(x['MWA_Word'])))
denominator_s1 = sts.apply(lambda x: sum(1 for w in x['Sent1_tokenized'] if w in C))

numerator_s2 = mwa.apply(lambda x: sum(alignments[1] in C if alignments else 0 for alignments in eval(x['MWA_Word'])))
denominator_s2 = sts.apply(lambda x: sum(1 for w in x['Sent2_tokenized'] if w in C))


mwa_prop = graphlab.SFrame({'n_s1': numerator_s1 , 'd_s1': denominator_s1, 
                           'n_s2': numerator_s2, 'd_s2': denominator_s2})

mwa_prop['prop_s1'] = mwa_prop.apply(lambda x: x['n_s1'] / x['d_s1'])
mwa_prop['prop_s2'] = mwa_prop.apply(lambda x: x['n_s2'] / x['d_s2'])

def harmonic(x, e):
    return (2*x['prop_s1']*x['prop_s1']) /(x['prop_s1'] + x['prop_s2'] + e)

epsilon = 1
mwa_prop['prop_harmonic'] = mwa_prop.apply(lambda x: harmonic(x, epsilon))

# Pywsd's Lemmatizer.
porter = PorterStemmer()
wnl = WordNetLemmatizer()
​
def lemmatize(ambiguous_word, pos=None, neverstem=False, 
              lemmatizer=wnl, stemmer=porter):
    """
    Tries to convert a surface word into lemma, and if lemmatize word is not in
    wordnet then try and convert surface word into its stem.
    
    This is to handle the case where users input a surface word as an ambiguous 
    word and the surface word is a not a lemma.
    """
    if pos:
        lemma = lemmatizer.lemmatize(ambiguous_word, pos=pos)
    else:
        lemma = lemmatizer.lemmatize(ambiguous_word)
    stem = stemmer.stem(ambiguous_word)
    # Ensure that ambiguous word is a lemma.
    if not wn.synsets(lemma):
        if neverstem:
            return ambiguous_word
        if not wn.synsets(stem):
            return ambiguous_word
        else:
            return stem
    else:
        return lemma

# Exact lemmas
punctuations = string.punctuation

def pywsd_lemmatize(list_of_list_of_str):
    for r in list_of_list_of_str:
        yield str([lemmatize(unicode(w.decode('utf8', 'ignore').strip(punctuations).lower())) for w in r]) 
    

lemmas = graphlab.SFrame({'Sent1_lemmatized': list(pywsd_lemmatize(sts['Sent1_tokenized'])),
                          'Sent2_lemmatized': list(pywsd_lemmatize(sts['Sent2_tokenized']))
                         })
                         
assert len(sts) == len(asiya) == len(meteor) == len(beer_reval) == len(mwa)

sts.add_columns(asiya)
sts.add_columns(meteor)
sts.add_columns(beer_reval)
sts.add_column(mwa_prop['prop_harmonic'], name='prop_harmonic')
sts.add_columns(lemmas)


sts.save('sts_all.csv', format='csv')
sts.save('sts_all.gl', format='binary')
```

**Comment by alvations** [comment]
I should probably close this issue, since it was some crazy cells with `eval(str)` -> None that caused the problem and not SFrame's failure. At least I learnt that it's not possible to save the SFrame if there are cells with `None`. I figured that if i cast them into strings, they would be "save-able".

**Comment by TobyRoseman** [comment]
@alvations - Thanks for code. After cloning the repository and installing nltk, I get the following error:
```
Traceback (most recent call last):
  File "repo.py", line 20, in <module>
    mwa = graphlab.SFrame.read_csv('sts_mwa.csv', delimiter='\t', column_type_hints=[str,str], quote_char='\0')
  File "/usr/local/lib/python2.7/dist-packages/graphlab/data_structures/sframe.py", line 1539, in read_csv
    **kwargs)[0]
  File "/usr/local/lib/python2.7/dist-packages/graphlab/data_structures/sframe.py", line 1099, in _read_csv_impl
    errors = proxy.load_from_csvs(internal_url, parsing_config, type_hints)
  File "/usr/local/lib/python2.7/dist-packages/graphlab/cython/context.py", line 49, in __exit__
    raise exc_type(exc_value)
RuntimeError: Runtime Exception. column_type_hints has different size from actual number of columns: column_type_hints.size()=2;number of columns=3
```

So I can't reproduce the problem and I'm not really understanding the issue. Some how you had a cell that evaluated to None?

If we can get a simple test to reproduce the issue (i.e. like a unit test), I'd be happy to look at it further.

**Comment by alvations** [comment]
@TobyRoseman sorry, i've missed out the header line in the `sts_mwa.csv`, now i've added it https://github.com/alvations/stasis/commit/9ce2e3e13cc22e6c3c6f033dd59a86c57da58b0e . The `column_type_hints` should be correct now.

**Comment by alvations** [comment]
And with [this script](https://drive.google.com/file/d/0B04oQzUfrOTjdFN6SGlQMlZtNUU/view?usp=sharing), by capturing the cells with `eval('None')` it resolves the problem.
