### ISSUE TITLE
SArray.apply lambda with file handle not serialized correctly

### ISSUE THREAD

**Issue by michaelbrooks** [dato-code/SFrame#247]
User reported receiving the following stacktrace when calling SArray.apply with a lambda function that uses an open file handle.

```
 Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/python_envs/graphlab/local/lib/python2.7/site-packages/graphlab/data_structures/sarray.py", line 1701, in apply
    return SArray(_proxy=self.__proxy__.transform(fn, dtype, skip_undefined, seed))
  File "/mnt/python_envs/graphlab/local/lib/python2.7/site-packages/graphlab/cython/context.py", line 49, in __exit__
    raise exc_type(exc_value)
RuntimeError: Runtime Exception. Runtime Exception. Exception in python callback function evaluation: 
TypeError("Required argument 'fileno' (pos 1) not found",): 
Traceback (most recent call last):
  File "graphlab/cython/cy_pylambda_workers.pyx", line 393, in graphlab.cython.cy_pylambda_workers._init_lambda
  File "graphlab/cython/cy_pylambda_workers.pyx", line 133, in graphlab.cython.cy_pylambda_workers.lambda_evaluator.__init__
TypeError: Required argument 'fileno' (pos 1) not found
```

Repro steps:

1. Download and extract the following geoip2 database: http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz
2. Pip install geoip2
3. Run the following script:

```python
import graphlab as gl
import geoip2.database

sf= gl.SFrame({'ip':['77.238.184.150']})

# Does not work!
reader = geoip2.database.Reader('GeoLite2-City.mmdb')
sf['ip'].apply(lambda x: reader.city(x).country.iso_code)
```

This workaround solves the problem:

```python
def apply_f(x):
    if 'reader' not in globals():
        globals()['reader'] = geoip2.database.Reader('GeoLite2-City.mmdb')
    reader = globals()['reader']
    return reader.city(x).country.iso_code

sf['ip'].apply(apply_f)
```

**Comment by ylow** [comment]
File handles cannot in general be serialized. This cannot really be fixed.
