### ISSUE TITLE
TypeError in Exception handling in _read_csv_impl

### ISSUE THREAD

**Issue by hershaw** [dato-code/SFrame#288]
Using `SFrame==1.9` and `python3.4`.

When trying to create an sframe from an s3 path that doesn't exist, I got the following:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/samuelhopkins/.virtualenvs/wrangle/lib/python3.4/site-packages/sframe/data_structures/sframe.py", line 1191, in _read_csv_impl
    errors = proxy.load_from_csvs(internal_url, parsing_config, type_hints)
  File "/Users/samuelhopkins/.virtualenvs/wrangle/lib/python3.4/site-packages/sframe/cython/context.py", line 49, in __exit__
    raise exc_type(exc_value)
RuntimeError: Runtime Exception. No files corresponding to the specified path (s3://invalid-path/).

During handling of the above exception, another exception occurred:


Traceback (most recent call last):
  File "/Users/samuelhopkins/cp/wrangle/test/test_cpio.py", line 65, in test_download_to_sframe
    sf_from_bucket = origcsvio.get_sframe(self.csvid)
  File "/Users/samuelhopkins/cp/wrangle/wrangle/cpio.py", line 109, in get_sframe
    return read_csv(cls.get_s3_url(name))
  File "/Users/samuelhopkins/cp/wrangle/wrangle/wrangle.py", line 12, in read_csv
    return SFrame.read_csv(identifier, na_values=[''])
  File "/Users/samuelhopkins/.virtualenvs/wrangle/lib/python3.4/site-packages/sframe/data_structures/sframe.py", line 1635, in read_csv
    **kwargs)[0]
  File "/Users/samuelhopkins/.virtualenvs/wrangle/lib/python3.4/site-packages/sframe/data_structures/sframe.py", line 1120, in _read_csv_impl
    verbose=verbose)
  File "/Users/samuelhopkins/.virtualenvs/wrangle/lib/python3.4/site-packages/sframe/data_structures/sframe.py", line 1635, in read_csv
    **kwargs)[0]
  File "/Users/samuelhopkins/.virtualenvs/wrangle/lib/python3.4/site-packages/sframe/data_structures/sframe.py", line 1193, in _read_csv_impl
    if type(e) == RuntimeError and "CSV parsing cancelled" in e.args[0]:
TypeError: argument of type 'RuntimeError' is not iterable
```

If I change the calls to `<string> in e.args[0]` to `<string> in str(e.args[0])` [here](https://github.com/dato-code/SFrame/blob/1d27a9d0f226b35b6191e84691b9c1ba2e162ed2/oss_src/unity/python/sframe/data_structures/sframe.py#L1133) and [here](https://github.com/dato-code/SFrame/blob/1d27a9d0f226b35b6191e84691b9c1ba2e162ed2/oss_src/unity/python/sframe/data_structures/sframe.py#L1193) I now get the following which is more correct:

```
Traceback (most recent call last):
  File "/Users/samuelhopkins/.virtualenvs/wrangle/lib/python3.4/site-packages/sframe/data_structures/sframe.py", line 1191, in _read_csv_impl
    errors = proxy.load_from_csvs(internal_url, parsing_config, type_hints)
  File "sframe/cython/cy_sframe.pyx", line 79, in sframe.cython.cy_sframe.UnitySFrameProxy.load_from_csvs
  File "sframe/cython/cy_sframe.pyx", line 87, in sframe.cython.cy_sframe.UnitySFrameProxy.load_from_csvs
RuntimeError: Runtime Exception. No files corresponding to the specified path (s3://invalid-path/).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/Users/samuelhopkins/cp/wrangle/test/test_cpio.py", line 65, in test_download_to_sframe
    sf_from_bucket = origcsvio.get_sframe(self.csvid)
  File "/Users/samuelhopkins/cp/wrangle/wrangle/cpio.py", line 109, in get_sframe
    return read_csv(cls.get_s3_url(name))
  File "/Users/samuelhopkins/cp/wrangle/wrangle/wrangle.py", line 12, in read_csv
    return SFrame.read_csv(identifier, na_values=[''])
  File "/Users/samuelhopkins/.virtualenvs/wrangle/lib/python3.4/site-packages/sframe/data_structures/sframe.py", line 1635, in read_csv
    **kwargs)[0]
  File "/Users/samuelhopkins/.virtualenvs/wrangle/lib/python3.4/site-packages/sframe/data_structures/sframe.py", line 1191, in _read_csv_impl
    errors = proxy.load_from_csvs(internal_url, parsing_config, type_hints)
  File "/Users/samuelhopkins/.virtualenvs/wrangle/lib/python3.4/site-packages/sframe/cython/context.py", line 49, in __exit__
    raise exc_type(exc_value)
RuntimeError: Runtime Exception. No files corresponding to the specified path (s3://invalid-path/).
```

**Comment by hershaw** [comment]
Ah, hadn't realize the changes were already made on master. My bad!
