### ISSUE TITLE
graphlab installation failure, solved

### ISSUE THREAD

**Issue by grfiv** [dato-code/SFrame#96]
Ubuntu 15.04 Python 2.7 IPython 4.0.0

Having used graphlab in the introductory section of your Coursera program I thought I would make sure I was still up-to-date per the instructions at the beginning of the Regression module

Following 
```
sudo -H pip install --upgrade graphlab-create
sudo -H pip install -U sframe
sudo reboot
```

```
ipython
import graphlab as gl
```

produced the following

```
In [2]: import graphlab as gl
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-4a710214f762> in <module>()
----> 1 import graphlab as gl

/usr/local/lib/python2.7/dist-packages/graphlab/__init__.py in <module>()
     52 from graphlab.util import set_runtime_config
     53 
---> 54 import graphlab.connect as _mt
     55 import graphlab.connect.aws as aws
     56 import visualization

/usr/local/lib/python2.7/dist-packages/graphlab/connect/__init__.py in <module>()
     29 """ The module usage metric tracking object """
     30 from graphlab.util.config import DEFAULT_CONFIG as _default_local_conf
---> 31 from graphlab.util.metric_tracker import MetricTracker as _MetricTracker
     32 
     33 

/usr/local/lib/python2.7/dist-packages/graphlab/util/metric_tracker.py in <module>()
     21 import uuid
     22 import copy as _copy
---> 23 import requests as _requests
     24 import sys
     25 import urllib as _urllib

/usr/local/lib/python2.7/dist-packages/requests/__init__.py in <module>()
     51 # Attempt to enable urllib3's SNI support, if possible
     52 try:
---> 53     from .packages.urllib3.contrib import pyopenssl
     54     pyopenssl.inject_into_urllib3()
     55 except ImportError:

/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py in <module>()
     68 _openssl_versions = {
     69     ssl.PROTOCOL_SSLv23: OpenSSL.SSL.SSLv23_METHOD,
---> 70     ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD,
     71     ssl.PROTOCOL_TLSv1: OpenSSL.SSL.TLSv1_METHOD,
     72 }

AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'
```

Looking at the error message and having noticed that your installation had moved **requests** back to an earlier level, I tried 

```
sudo -H pip install -U pyopenssl
sudo -H pip install -U urllib3
sudo -H pip install -U requests
```

... and this seemed to do the trick.

**Comment by dbickson** [comment]
Thanks George for your kind updates. This will definitely be useful for other users.

**Comment by grfiv** [comment]
I think I may have spoken too soon...

```
george@grfiv:~$ ipython
Python 2.7.10 (default, Oct 14 2015, 16:09:02) 
Type "copyright", "credits" or "license" for more information.

IPython 4.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import graphlab

In [2]: import sframe
[INFO] Using MetricMock instead of real metrics, mode is: QA
[ERROR] unity_server launched with command ("/usr/local/lib/python2.7/dist-packages/graphlab/unity_server" --help) failed 
return code: 126
message: /bin/sh: 1: /usr/local/lib/python2.7/dist-packages/graphlab/unity_server: Permission denied

[ERROR] /bin/sh: 1: /usr/local/lib/python2.7/dist-packages/graphlab/unity_server: Permission denied

[ERROR] unity_server launched with command ("/usr/local/lib/python2.7/dist-packages/graphlab/unity_server" --help) failed 
return code: 126
message: /bin/sh: 1: /usr/local/lib/python2.7/dist-packages/graphlab/unity_server: Permission denied

[ERROR] /bin/sh: 1: /usr/local/lib/python2.7/dist-packages/graphlab/unity_server: Permission denied

[ERROR] unity_server launched with command ("/usr/local/lib/python2.7/dist-packages/graphlab/unity_server" --help) failed 
return code: 126
message: /bin/sh: 1: /usr/local/lib/python2.7/dist-packages/graphlab/unity_server: Permission denied

[ERROR] /bin/sh: 1: /usr/local/lib/python2.7/dist-packages/graphlab/unity_server: Permission denied

[ERROR] unity_server launched with command ("/usr/local/lib/python2.7/dist-packages/graphlab/unity_server" --help) failed 
return code: 126
message: /bin/sh: 1: /usr/local/lib/python2.7/dist-packages/graphlab/unity_server: Permission denied

[ERROR] /bin/sh: 1: /usr/local/lib/python2.7/dist-packages/graphlab/unity_server: Permission denied

[ERROR] unity_server launched with command ("/usr/local/lib/python2.7/dist-packages/graphlab/unity_server" --help) failed 
return code: 126
message: /bin/sh: 1: /usr/local/lib/python2.7/dist-packages/graphlab/unity_server: Permission denied

[ERROR] /bin/sh: 1: /usr/local/lib/python2.7/dist-packages/graphlab/unity_server: Permission denied

[ERROR] unity_server launched with command ("/usr/local/lib/python2.7/dist-packages/graphlab/unity_server" --help) failed 
return code: 126
message: /bin/sh: 1: /usr/local/lib/python2.7/dist-packages/graphlab/unity_server: Permission denied

[ERROR] /bin/sh: 1: /usr/local/lib/python2.7/dist-packages/graphlab/unity_server: Permission denied

[ERROR] unity_server launched with command ("/usr/local/lib/python2.7/dist-packages/graphlab/unity_server" --help) failed 
return code: 126
message: /bin/sh: 1: /usr/local/lib/python2.7/dist-packages/graphlab/unity_server: Permission denied

[ERROR] /bin/sh: 1: /usr/local/lib/python2.7/dist-packages/graphlab/unity_server: Permission denied

[ERROR] unity_server launched with command ("/usr/local/lib/python2.7/dist-packages/graphlab/unity_server" --help) failed 
return code: 126
message: /bin/sh: 1: /usr/local/lib/python2.7/dist-packages/graphlab/unity_server: Permission denied

[ERROR] /bin/sh: 1: /usr/local/lib/python2.7/dist-packages/graphlab/unity_server: Permission denied

[ERROR] unity_server launched with command ("/usr/local/lib/python2.7/dist-packages/graphlab/unity_server" --help) failed 
return code: 126
message: /bin/sh: 1: /usr/local/lib/python2.7/dist-packages/graphlab/unity_server: Permission denied

[ERROR] /bin/sh: 1: /usr/local/lib/python2.7/dist-packages/graphlab/unity_server: Permission denied

[ERROR] unity_server launched with command ("/usr/local/lib/python2.7/dist-packages/graphlab/unity_server" --help) failed 
return code: 126
message: /bin/sh: 1: /usr/local/lib/python2.7/dist-packages/graphlab/unity_server: Permission denied

[ERROR] /bin/sh: 1: /usr/local/lib/python2.7/dist-packages/graphlab/unity_server: Permission denied

[ERROR] unity_server launched with command ("/usr/local/lib/python2.7/dist-packages/graphlab/unity_server" --help) failed 
return code: 126
message: /bin/sh: 1: /usr/local/lib/python2.7/dist-packages/graphlab/unity_server: Permission denied

[ERROR] /bin/sh: 1: /usr/local/lib/python2.7/dist-packages/graphlab/unity_server: Permission denied


In [3]: 

```

**Comment by dbickson** [comment]
This permission issue may be resulting from an installation as root/adminstrator while you try to operate the software as a normal (or another user). Let's move the discussion to our support - support@dato.com
Please email this error report to there and we will help.
Thanks

**Comment by sakuraliu** [comment]
import graphlab as gl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Anaconda\envs\gl-env\lib\site-packages\graphlab\__init__.py", line 50, in <module>
    import graphlab.connect as _mt
AttributeError: 'module' object has no attribute 'connect'
